stages:
- test

test:
        image: python:latest
        script:
        - python3 setup.py install
        - youtube-sm --init subscription_manager
        - youtube-sm
        - youtube-sm --html -l [youtube] UC-lHJZR3Gqxm24_Vd_AJ5Yw -m list -t -1 --output lol.html -r
        - youtube-sm --ultra-html -l [youtube] UCEcNXmr7DYq1XxpWHSxaN0w -m raw -t -1 -r
        only:
        - master


